services:
  signal-desktop-gui:
    image: annegerben/signal-desktop:latest
    container_name: signal-desktop
    shm_size: 2g
    volumes:
      - /data/signal:/config
    ports:
      - 5800:5800
    environment:
      - TZ=Europe/Amsterdam
      - DARK_MODE=1
    restart: unless-stopped

