name: Docker Build and Push

on:
  push:
    branches:
      - develop
    paths:
      - 'signal.version' # Triggert alleen als de versie is aangepast
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SIGNAL }} # Consistent gebruik van je PAT
          ref: develop

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            annegerben/signal-desktop-gui:latest
            annegerben/signal-desktop-gui:${{ steps.get_version_tag.outputs.version }}
        # We moeten de versie even inlezen voor de tag
        id: build_step

      # Extra stap om de versie uit het bestand te halen voor de Docker tag
      - name: Get version for tag
        id: get_version_tag
        run: echo "version=$(cat signal.version)" >> $GITHUB_OUTPUT
